#!/usr/bin/env bash
# -------------------------------------------------------------------------
# rstc: A simple wrapper script for rustic backup tool
# -------------------------------------------------------------------------
# GitHub: https://github.com/tricarte/rstc
# -------------------------------------------------------------------------

#--------------------------
# Utility functions
#--------------------------

red='\033[0;31m'
green='\033[0;32m'
purple='\033[0;35m'
normal='\033[0m'

# Utility functions
# https://github.com/CodelyTV/dotly/blob/master/installer#L21
_w() {
  local -r text="${1:-}"
  echo -e "$text"
}
_a() { _w " > $1"; }                 # Alert
_e() { _a "${red}$1${normal}" >&2; } # Error
_s() { _a "${green}$1${normal}"; }   # Success

#--------------------------
# End of Utility functions
#--------------------------

#--------------------------
# Prerequisites
#--------------------------

RUSTIC=$(command -v rustic)
if [[ ! $RUSTIC ]]; then
  _e "Rustic is not installed."
  exit 1
fi

FZF=$(command -v fzf)
if [[ -z $FZF ]]; then
  _e "FZF is not installed."
  exit 1
fi

LF=$(command -v lf)
if [[ -z $LF ]]; then
  _e "lf is not installed."
  exit 1
fi

if [[ -n "$XDG_CURRENT_DESKTOP" ]]; then
  NOTIFYBIN=$(command -v notify-send)
fi

if [[ ! -f /etc/.rustic-pass.gpg ]]; then
  _w ""
  _a "/etc/.rustic-pass.gpg does not exist. Creating..."
  _w ""
  _w "First give a passphrase for this encrypted file,"
  _w "then type the password to be used when working with backup repositories,"
  _w "then press the Enter key and then Ctrl+D to exit."
  _w "BEWARE! What you enter will be visible on the screen."
  _w ""
  tmp="$(mktemp --dry-run)"
  # if gpg -q --pinentry-mode loopback --output "${tmp}" --symmetric -; then
  if gpg -q --output "${tmp}" --symmetric -; then
    if [[ -f "${tmp}" ]]; then
      user="$(whoami)"
      sudo mv "${tmp}" /etc/.rustic-pass.gpg &&
        sudo chown "${user}:${user}" /etc/.rustic-pass.gpg &&
        sudo chmod 600 /etc/.rustic-pass.gpg &&
        _w "Password file successfully created." &&
        exit
    fi
  fi
fi

if [[ ! -f /etc/.rustic-pass.gpg ]]; then
  _e "Password file /etc/.rustic-pass.gpg could not be created."
  exit 1
fi

#-------------------------
# End of prerequisites
#-------------------------

#-------------------------------------------------------------------
# Global Option Parsing
#-------------------------------------------------------------------
PARAMS=""
while (("$#")); do
  case "$1" in
  -y | --yes)
    PROCEED=1
    shift # Pop the first element off the array on each iteration.
    ;;
  -h | --help)
    SUBHELP=1
    shift
    ;;
  -e | --edit)
    EDIT=1
    shift
    ;;
  --* | -*) # unsupported flags
    _e "Error: Unsupported flag $1" >&2
    exit 1
    ;;
  *) # preserve positional arguments
    PARAMS="$PARAMS $1"
    shift
    ;;
  esac
done

eval set -- "$PARAMS"

progname=$(basename "$0")
subcommand=$1

function doAll() {
  if [[ -d "${HOME}/.config/rustic" ]]; then
    for config in "${HOME}"/.config/rustic/*.toml; do
      eval "local $(grep -E ^repository "$config" | tr -d ' ')"
      profile=$(basename "$config" .toml)
      if [[ -d "$repository" ]]; then
        case $1 in
        forget)
          $RUSTIC --no-progress --log-level OFF -P "$profile" forget --prune --instant-delete || break
          ;;
        backup)
          $RUSTIC --no-progress --log-level OFF -P "$profile" backup || break
          ;;
        esac
      else
        _e "Repository for profile \"$profile\" is not accessible.
It is pointing to ${repository}."
        exit 1
      fi
    done
  fi
}

function edit() {
  local profile="$1"
  if [[ -n "$VISUAL" ]]; then
    $VISUAL "${profile}"
    exit
  elif [[ -n "$EDITOR" ]]; then
    $EDITOR "${profile}"
    exit
  else
    xdg-open "${profile}"
  fi
}

#----------------
#  SUBCOMMANDS
#----------------

#------------------------------------------------------
# Main subcommand controller
#------------------------------------------------------
function sub_default() {
  _w "
${progname}: A wrapper script for rustic. Works only with backup profiles.

    Usage: ${purple}${progname} <subcommand> [optional_profile_name] OPTIONS${normal}

Subcommands:

    ${purple}backup${normal}          Backup all profiles or a specific profile.
    ${purple}forget${normal}          Prune snapshots according to 'forget' settings in the profile.
    ${purple}create${normal}          Create a new profile.
    ${purple}init${normal}            Initialize the profile you have previously created with 'create' command.
    ${purple}edit${normal}            Start editing the profile in your configured text editor.
    ${purple}go${normal}              Run backup and forget in one go.
    ${purple}snapshots${normal}       List snapshots of a backup profile.

Generally a backup procedure should go like this:

    ${progname} create profile_name
    ${progname} edit profile_name
    ${progname} init profile_name
    ${progname} backup profile_name

For help with each subcommand run:
${purple}$progname <subcommand> -h|--help${normal}
"
  exit
}
export -f sub_default

function sub_create() {
  if [[ $SUBHELP ]]; then
    _w "Usage: $progname create [profile_name]"
    _w ""
    _w "       Create a new profile in ~/.config/rustic."
    _w "       Give the profile name without toml extension."
    _w ""
    return
  fi

  profile="$1"

  if [[ -z "$profile" ]]; then
    _e "You did not specify the profile name."
    exit 1
  fi

  if [[ -f "${HOME}/.config/rustic/${profile}.toml" ]]; then
    _w "Profile already exists."
    exit
  fi

  user=$(getent passwd 1000 | cut -d':' -f1)

  media=$(lsblk -o MOUNTPOINT | grep -E ^/media/"${user}" | head -n1)
  if [[ -d $media ]]; then
    media=$(basename "${media}")
  fi

  cat <<EOT >"${HOME}/.config/rustic/${profile}.toml"
[repository]
repository = "/media/${user}/${media:=change_me_deviceID}/rustic-backups/${profile}"
# password-file =  "/root/key-rustic"
no-cache = true # no cache needed for local repository
# password-command = "gpg --no-tty -q -d /etc/.rustic-pass.gpg"
# password-command = "gpg -q -d --pinentry-mode loopback /etc/.rustic-pass.gpg"
password-command = "gpg -q -d /etc/.rustic-pass.gpg"

[forget]
# keep-hourly = 20
# keep-daily = 14
keep-daily = 3
# keep-weekly = 8
# keep-monthly = 24
# keep-yearly = 10
EOT

  if [[ -f "${HOME}/.config/rustic/${1}.toml" ]]; then
    if [[ $EDIT ]]; then
      profile="${HOME}/.config/rustic/${profile}.toml"
      edit "$profile"
    else
      _w "Profile successfully created."
    fi
  else
    _e "Profile could not be created."
    exit 1
  fi
}
export -f sub_create

function sub_edit() {
  if [[ $SUBHELP ]]; then
    _w "Usage: $progname edit [profile_name]"
    _w ""
    _w "       Start editing the profile in your configured text editor."
    _w ""
    return
  fi

  profile="$1"

  if [[ -z "$profile" ]]; then
    _e "You did not specify the profile name."
    exit 1
  fi

  if [[ ! -f "${HOME}/.config/rustic/${profile}.toml" ]]; then
    _e "Profile does not exist."
    exit 1
  fi

  edit "${HOME}/.config/rustic/${profile}.toml"
  exit
}
export -f sub_edit

function sub_init() {
  if [[ $SUBHELP ]]; then
    _w "Usage: $progname init [profile_name]"
    _w ""
    _w "       Initialize the profile you have previously created with 'create' command."
    _w ""
    return
  fi

  profile="$1"

  if [[ -z "$profile" ]]; then
    _e "You did not specify the profile name."
    exit 1
  fi

  if [[ ! -f "${HOME}/.config/rustic/${profile}.toml" ]]; then
    _e "Profile does not exist."
    exit 1
  fi

  $RUSTIC -P "${profile}" init
}
export -f sub_init

function sub_backup() {
  if [[ $SUBHELP ]]; then
    _w "Usage: $progname backup [profile_name] [-y|--yes]"
    _w ""
    _w "       If no profile name is provided, then all profiles in '$HOME/.config/rustic' will be backed up."
    _w "       Profile names must be given without 'toml' file extension."
    _w "       Use -y or --yes to backup all profiles without confirmation."
    _w ""
    return
  fi

  profile="$1"

  if [[ -z $profile ]]; then
    if [[ $PROCEED ]]; then
      doAll backup
    else
      read -p "All profiles will be backed up. Proceed? (y/n): " -n 1 -er answer
      if [[ "$answer" =~ ^Y|y$ ]]; then
        doAll backup
      else
        echo "Backup aborted."
        exit
      fi
    fi
  else
    p="$HOME/.config/rustic/${profile}.toml"
    if [[ -f "${p}" ]]; then
      eval "$(grep -E ^repository "${p}" | tr -d ' ')"
      if [[ -n "${repository}" ]]; then
        if [[ -d "${repository}" ]]; then
          $RUSTIC --no-progress --log-level OFF -P "$profile" backup
        else
          _e "Repository for profile \"$profile\" is not accessible."
          _e "It is pointing to ${repository}."
          exit
        fi
      fi
    else
      _e "No such profile in '$HOME/.config/rustic'."
      exit 1
    fi
  fi

  return
}
export -f sub_backup

function sub_forget() {
  if [[ $SUBHELP ]]; then
    _w "Usage: $progname forget [profile_name] [-y|--yes]"
    _w ""
    _w "       If no profile name is provided, then all profiles in '$HOME/.config/rustic' will be cleaned"
    _w "       according to their forget settings.."
    _w "       Profile names must be given without 'toml' file extension."
    _w "       Use -y or --yes to clean all profiles without confirmation."
    _w ""
    return
  fi

  profile="$1"

  if [[ -z $profile ]]; then
    if [[ $PROCEED ]]; then
      doAll forget
    else
      read -p "All profiles will be cleaned. Proceed? (y/n): " -n 1 -er answer
      if [[ "$answer" =~ ^Y|y$ ]]; then
        doAll forget
      else
        echo "Cleaning aborted."
        exit
      fi
    fi
  else
    p="$HOME/.config/rustic/${profile}.toml"
    if [[ -f "${p}" ]]; then
      eval "$(grep -E ^repository "${p}" | tr -d ' ')"
      if [[ -n "${repository}" ]]; then
        if [[ -d "${repository}" ]]; then
          $RUSTIC -P "${profile}" forget --prune --instant-delete
        else
          _e "Repository for profile \"$profile\" is not accessible."
          _e "It is pointing to ${repository}."
          exit
        fi
      fi
    else
      _e "No such profile in '$HOME/.config/rustic'."
      exit 1
    fi
  fi

  return
}
export -f sub_forget

function sub_go() {
  if [[ $SUBHELP ]]; then
    _w "Usage: $progname go [profile_name]"
    _w ""
    _w "       Run backup and forget in one go for a single or all profiles."
    _w ""
    return
  fi

  PROFILE="${1}"

  if [[ -n "${PROFILE}" ]]; then
    if [[ -f "${HOME}/.config/rustic/${PROFILE}.toml" ]]; then
      $progname backup "${PROFILE}" && $progname forget "${PROFILE}"
      exit
    else
      _e "Profile does not exist."
      exit 1
    fi
  else
    $progname backup -y && $progname forget -y
  fi

  return
}
export -f sub_go

function sub_restore() {
  if [[ $SUBHELP ]]; then
    _w "Usage: $progname restore profile_name [-y|--yes]"
    _w ""
    _w "       Restore a backup profile that is stored in '~/.config/rustic'"
    _w "       to a location of your choice. Profile names must be given "
    _w "       without 'toml' file extension."
    _w ""
    return
  fi

  profile="$1"
  if [[ -z "${profile}" ]]; then
    $progname restore --help
    return
  fi

  if [[ -f "${HOME}/.config/rustic/${profile}.toml" ]]; then
    _w "Getting repository information..."
    if $RUSTIC -P "${profile}" repoinfo >/dev/null 2>&1; then
      json=$(
        $RUSTIC --log-level OFF -P "${profile}" snapshots latest --json |
          jq -r '.[][0].paths[]' |
          sed -e '/^$/d'
      )

      paths=$(
        printf '%s' "${json}" |
          $FZF --bind 'ctrl-a:toggle-all' --multi \
            --header='Use Tab/Shift+Tab to (de)select multiple paths, Ctrl+A to toggle selection.'
      )

      if [[ -z "${paths}" ]]; then
          _e 'You did not choose any path to restore!'
          exit 1
      fi

      tmp="$(mktemp)"
      $LF -single -config NONE \
        -command 'echo Select a destination directory...' \
        -command 'set dironly' \
        -command 'set nopreview' \
        -command 'set incsearch' \
        -last-dir-path="${tmp}"

      if [[ -f "${tmp}" ]]; then
        destination="$(cat "${tmp}")"
        rm -f "${tmp}"
        # FIXME: /tmp/tmp.dir/home/user/some-backup
        # /tmp/tmp.dir/* can be copied to / (root)
        # even though the / is not writable.
        if [[ -w "${destination}" ]]; then
          if [[ ! $PROCEED ]]; then
              printf '\n%s\n%s\n' "Path(s) to restore:" "${paths}"
            printf '\n%s\n' "Destination directory: ${destination}"
            read -p "Proceed to restore?  (y/n): " -r
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
              _w "Restore aborted."
              return 1
            fi
          fi
          while IFS=$'\n' read -r item; do
            _w "Restoring ${item}..."
            tmp="$(mktemp -d)"
            if ! $RUSTIC --log-level OFF --no-progress -P "${profile}" restore latest --filter-paths "${item}" "${tmp}"; then
              _e "Restore aborted due to error!"
              _e "${item} could not be restored to ${destination}."
              return 1
            fi
            cp -R -f "${tmp}"/* "${destination}"/
            rm -R -f "${tmp}"
            _w ""
          done < <(printf '%s\n' "${paths}")
          _w "Restore to ${destination} completed!"
        else
          _e "Selected destination '${destination}' is not writable."
          return 1
        fi
      fi
    else
      _e "The directory containing the repository is not accessible."
      exit 1
    fi
  else
    _e "No such profile in '${HOME}/.config/rustic'."
    exit 1
  fi

  return
}
export -f sub_restore

function sub_snapshots() {
  if [[ $SUBHELP ]]; then
    _w "Usage: $progname snapshots [profile_name]"
    _w ""
    _w "       List the snapshots of a profile in '$HOME/.config/rustic'."
    _w "       Profile names must be given without 'toml' file extension."
    _w ""
    return
  fi

  profile="$1"

  if [[ -z $profile ]]; then
      _e "Provide a profile name from '$HOME/.config/rustic'."
      exit 1
  else
    p="$HOME/.config/rustic/${profile}.toml"
    if [[ -f "${p}" ]]; then
      eval "$(grep -E ^repository "${p}" | tr -d ' ')"
      if [[ -n "${repository}" ]]; then
        if [[ -d "${repository}" ]]; then
          $RUSTIC --no-progress --log-level OFF -P "$profile" snapshots
        else
          _e "Repository for profile \"$profile\" is not accessible."
          _e "It is pointing to ${repository}."
          exit
        fi
      fi
    else
      _e "No such profile in '$HOME/.config/rustic'."
      exit 1
    fi
  fi

  return
}
export -f sub_snapshots

#-------------------------
#  sub_command handling
#-------------------------
case $subcommand in
"" | "-h" | "--help" | "help")
  sub_default
  ;;
*)
  shift
  if [[ "$(type -t "sub_${subcommand}")" == 'function' ]]; then
    "sub_${subcommand}" "$@"
    exit $?
  else
    _e "Error: '${subcommand}' is not a known subcommand." >&2
    _e "Run '${progname} --help' for a list of known subcommands." >&2
    exit 1
  fi
  ;;
esac
